export const data = {
  sharePuzzle: "分享拼图",
  shareLink: "分享链接",
  embedCode: "嵌入代码",
  copySuccess: "复制成功",
  copyFailed: "复制失败",
  shareLinkDescription: "复制此链接分享给好友，让他们也来体验这个拼图",
  embedDescription: "将此代码嵌入到您的网站或博客中，分享这个拼图",
  previewEmbed: "嵌入预览",
  embedPreviewPlaceholder: "嵌入后的拼图将显示在这里",
  createCategory: "创建分类",
  categoryName: "分类名称",
  categoryNamePlaceholder: "请输入分类名称",
  categoryDescription: "分类描述",
  categoryDescriptionPlaceholder: "请输入分类描述（可选）",
  categoryNameRequired: "分类名称不能为空",
  createCategoryFailed: "创建分类失败",

  createGroup: "创建分组",
  groupName: "分组名称",
  groupNamePlaceholder: "请输入分组名称",
  groupDescription: "分组描述",
  groupDescriptionPlaceholder: "请输入分组描述（可选）",
  groupNameRequired: "分组名称不能为空",
  categoryRequired: "请选择所属分类",
  createGroupFailed: "创建分组失败",

  createTag: "创建标签",
  tagName: "标签名称",
  tagNamePlaceholder: "请输入标签名称",
  tagDescription: "标签描述",
  tagDescriptionPlaceholder: "请输入标签描述（可选）",
  tagNameRequired: "标签名称不能为空",
  createTagFailed: "创建标签失败",

  category: "所属分类",
  creating: "创建中...",
  create: "创建",
  featuresTitle: "主要功能",
  faqTitle: "常见问题",
  websiteTitle: "拼图挑战 - 在线拼图社区 | 创建和玩拼图",
  homeH1: "创建、分享和解决数字拼图",
  exploreH1: "发现世界各地的拼图",
  exploreH21: "热门拼图",
  exploreH22: "最新创作",
  createH1: "在1步中构建您的独特拼图",
  createH2: "选择您的画布：图片、颜色或表情",
  createH3: "解决其他人创建的拼图",
  gameH1: "玩 {puzzleName} - {difficulty} 模式",
  websiteDescription:
    "创建个性化拼图，使用图片、颜色、表情和文字。与全球社区一起玩拼图，支持多种语言。免费在线拼图制作器，实时协作功能。",
  websiteKeywords:
    "拼图制作器, 在线拼图制作器, 自定义数字拼图, 在线玩拼图, 协作拼图解决, 多语言拼图平台",

  completed: "胜利",
  failed: "失败",
  notGameRecord: "暂无游戏记录",
  unknown: "未知",
  gameDuration: "游戏时长",
  viewDetails: "查看详情",
  myGameRecord: "我的游戏记录",
  siteTitle: "拼图挑战",
  home: "首页",
  explore: "发现",
  puzzle: "拼图编辑器",
  leaderboard: "排行榜",
  categories: "分类",
  groups: "群组",
  tags: "标签",
  search: "搜索拼图 🧩...",
  createPuzzle: "创建拼图 🧩",
  about: "关于我们",
  siteDescription:
    "拼图挑战是一个充满乐趣的在线拼图社区，让我们一起享受拼图的乐趣。",
  contact: "联系我们",
  email: "contact@puzzlechallenge.com",
  copyright: "© 2024 拼图挑战. 保留所有权利.",
  createRecord: "创建记录",
  all: "全部",
  draft: "待审核",
  published: "已发布",
  deleted: "已删除",
  challenge: "挑战",
  author: "作者",
  featuredCollections: "精选主题",
  view: "查看",
  searchError: "搜索过程中发生错误，请稍后重试",
  searchTitle: "搜索拼图 🧩...",
  searching: "搜索中...",
  previousPage: "上一页",
  nextPage: "下一页",
  noResults: "未找到匹配的原子",
  tryDifferentKeywords: "尝试使用不同的关键词搜索",
  myPuzzles: "我创建的拼图",
  noPuzzles: "暂无创建拼图",
  createPuzzles: "去创建一些拼图吧",
  pageLabel: "第 {page} 页，共 {totalPages} 页",
  imagePuzzle: "图片拼图",
  solidPuzzle: "纯色拼图",
  gradientPuzzle: "渐变拼图",
  emojiPuzzle: "Emoji拼图",
  patternPuzzle: "图案拼图",
  textPuzzle: "文字拼图",
  shapePuzzle: "形状拼图",
  pleaseUploadImage: "请先上传图片",
  atomDataValidationFailed: "拼图数据验证失败",
  atomUpdatedSuccess: "拼图更新成功",
  atomUpdatedFailed: "拼图更新失败",
  atomCreatedSuccess: "拼图创建成功",
  atomCreatedFailed: "拼图创建失败",
  pleaseLogin: "请先登录",
  pleaseLoginDescription: "请先登录，才能创建拼图",
  updatePuzzle: "更新拼图",
  uploadImage: "上传的图片",
  dragDropImage: "拖放图片到这里，或者",
  selectImage: "选择图片",
  supportImageFormat: "支持 JPG、PNG、WebP 格式，建议尺寸 1920x1080 像素",
  selectCategory: "选择分类",
  selectEmoji: "选择表情",
  backgroundColor: "背景颜色",
  emojiRotation: "旋转角度",
  presetGradient: "预设渐变",
  gradientType: "渐变类型",
  gradientColors: "渐变颜色 ({colors}个)",
  addColor: "添加颜色",
  gradientAngle: "渐变角度: {angle}°",
  linearGradient: "线性渐变",
  radialGradient: "径向渐变",
  patternType: "图案类型",
  patternPresets: "图案预设",
  patternSize: "图案大小: {size}px",
  patternSpacing: "图案间距: {spacing}px",
  lineWidth: "线条宽度: {lineWidth}px",
  patternRotation: "旋转角度: {rotation}°",
  patternColor: "图案颜色",
  previewEffect: "预览效果",
  puzzlePreview: "拼图预览",
  puzzlePreviewArea: "拼图预览区域",
  puzzleType: "拼图类型",
  expectedDifficulty: "预计难度",
  expectedUseTime: "预计用时",
  puzzleSettings: "拼图设置",
  puzzleTitle: "拼图标题",
  puzzleTitlePlaceholder: "请输入拼图标题",
  puzzleDescription: "拼图描述",
  puzzleDescriptionPlaceholder: "请输入拼图描述",
  puzzleCategory: "拼图分类",
  pleaseSelectCategory: "请先选择分类",
  puzzleGroup: "拼图分组",
  selectGroup: "选择分组",
  searchTags: "搜索标签",
  maxAddTags: "最多添加 5 个标签",
  loading: "加载中...",
  noMatchingTags: "无匹配标签",
  puzzlePieces: "拼图数量",
  puzzlePiecesMoreDifficult: "拼图数量越多，难度越大",
  customPuzzleSize: "自定义拼图尺寸",
  puzzleWidth: "宽度 (像素)",
  puzzleWidthPlaceholder: "自动",
  puzzleHeight: "高度 (像素)",
  puzzleHeightPlaceholder: "自动",
  puzzleStyle: "拼图样式",
  puzzleEdgeSize: "拼图边缘大小",
  puzzleEdgeSizePlaceholder: "请输入拼图边缘大小",
  puzzleSizeNotSet: "不设置时将使用原图尺寸",
  puzzleTags: "拼图标签",
  puzzleEdgeRandomness: "拼图边缘随机度",
  puzzleSeed: "随机种子",
  puzzleLineColor: "拼图线条颜色",
  puzzleLineWidth: "拼图线条宽度",
  puzzleLineWidthPlaceholder: "请输入拼图线条宽度",
  piecesOptionLabel: "{value} 片 ({tilesX}×{tilesY})",
  shapeType: "形状类型",
  circle: "圆形",
  square: "正方形",
  triangle: "三角形",
  star: "星形",
  heart: "心形",
  polygon: "多边形",
  spiral: "螺旋",
  flower: "花朵",
  shapeSize: "图形大小: {value}px",
  repeatMode: "重复模式",
  centered: "居中重叠",
  tiled: "网格平铺",
  random: "随机分布",
  repeatTimes: "图形重复次数: {value}",
  repeatGap: "重复间距: {value}px",
  randomRotation: "随机旋转",
  rotation: "旋转角度: {value}deg",
  shapeColor: "图形颜色",
  borderWidth: "边框宽度: {value}px",
  borderColor: "边框颜色",
  polygonSides: "多边形边数: {value}",
  flowerPetals: "花朵花瓣数: {value}",
  mint: "薄荷绿",
  skyBlue: "天空蓝",
  lightPurple: "淡紫色",
  coralPink: "珊瑚粉",
  goldenFlower: "金盏花",
  lavender: "薰衣草",
  tiffanyBlue: "蒂芙尼蓝",
  roseRed: "玫瑰红",
  lemonYellow: "柠檬黄",
  oceanBlue: "海洋蓝",
  graphiteBlack: "石墨黑",
  pearlWhite: "珍珠白",
  presetColors: "预设颜色",
  customColor: "自定义颜色",
  hexColorCode: "#HEX颜色码",
  apply: "应用",
  textMode: "文字模式",
  normal: "标准文本",
  randomText: "随机字符",
  tiledText: "平铺文本",
  text: "输入文字",
  textPlaceholder: "在这里输入文字...",
  textRepeat: "重复次数: {value}",
  randomSize: "随机大小",
  randomColor: "随机颜色",
  colorVariation: "颜色变化程度: {value}",
  font: "字体",
  sansSerif: "无衬线体",
  serif: "衬线体",
  monospace: "等宽字体",
  cursive: "草书",
  fantasy: "幻想体",
  microsoftYaHei: "微软雅黑",
  simSun: "宋体",
  kaiTi: "楷体",
  fontSize: "字体大小: {value}px",
  alignment: "对齐方式",
  left: "左对齐",
  center: "居中",
  right: "右对齐",
  bold: "粗体",
  italic: "斜体",
  textColor: "文字颜色",
  useTime: "约 {value} 分钟",
  pieces: "{value} 片",
  difficulty: "{value}",
  like: "点赞成功",
  unlike: "取消点赞成功",
  favorite: "收藏成功",
  unfavorite: "取消收藏成功",
  error: "操作失败，请稍后重试",
  group: "推荐🧩",
  share: "分享",
  featured: "精选",
  unfeatured: "取消精选",
  publish: "发布",
  unpublish: "取消发布",
  start: "开始拼图",
  startGame: "开始拼图",
  reset: "重新开始",
  exit: "退出游戏",
  complete: "完成拼图",
  time: "用时",
  piecesUnit: "片",
  difficultyLabel: "难度",
  surrounding: "环绕模式",
  surroundingDescription: "拼图块围绕在画布四周",
  centerScatter: "中心扩散",
  centerScatterDescription: "拼图块从中心向外散开分布",
  uniformDistribution: "均匀分散",
  uniformDistributionDescription: "拼图块均匀分布在整个画布上",
  black: "黑色",
  white: "白色",
  gray: "灰色",
  blue: "蓝色",
  green: "绿色",
  red: "红色",
  restartGame: "重新开始",
  exitGame: "退出游戏",
  completeGame: "完成拼图",
  verifyPuzzle: "验证拼图",
  autoArrange: "自动排列",
  selectBackgroundTexture: "选择背景纹理",
  readyToStart: "准备开始",
  gameSettings: "游戏设置",
  confirm: "确定并重新开始",
  cancel: "取消",
  distributionStrategy: "分布策略",
  lineColor: "线条颜色",
  lineWidthLabel: "线条宽度",
  puzzleVerified: "拼图验证",
  puzzleVerifiedDescription: "验证拼图是否正确",
  selectPuzzlePieces: "选择拼图数量",
  selectDistributionStrategy: "选择分布策略",
  selectLineColor: "选择线条颜色",
  selectLineWidth: "选择线条宽度",
  puzzleVerifiedSuccess: "拼图验证成功",
  puzzleVerifiedFailed: "拼图验证失败",
  continue: "继续",
  pause: "暂停",
  reset2: "重置",
  preview: "预览",
  grid: "网格",
  panning: "拖动模式",
  settings: "设置",
  freePanning: "自由拖动",
  bestTime: "最佳用时",
  patternGrid: "网格",
  patternDots: "圆点",
  patternLines: "线条",
  patternCircles: "圆环",
  patternTriangles: "三角形",
  patternZigzag: "锯齿线",
  patternWaves: "波浪线",
  patternCheckerboard: "棋盘格",
  patternHexagons: "六边形",
  patternStars: "星星",
  patternCrosshatch: "交叉线",
  patternPolkaDots: "波点",
  patternDiamonds: "菱形",
  patternStripes: "条纹",
  patternConfetti: "彩纸",
  patternHoneycomb: "蜂巢",
  solid: "纯色",
  gradient: "渐变",
  pattern: "纹理",
  easy: "简单",
  medium: "中等",
  hard: "困难",
  veryHard: "非常困难",
  faqItems: [
    {
      question: "如何在没有设计技能的情况下创建拼图？",
      answer:
        "我们的拖拽式编辑器带有50+模板，非常容易使用。只需单击添加元素，并使用AI辅助的布局建议。",
    },
    {
      question: "玩拼图是否免费？",
      answer:
        "是的！所有社区拼图100%免费玩。高级创作者获得分析仪表盘和商业使用权。",
    },
    {
      question: "语言设置如何工作？",
      answer:
        "自动将标题/描述翻译成12种语言。拼图内容保持原创语言，以确保真实性。",
    },
    {
      question: "我能私下分享拼图吗？",
      answer: "是的！生成密码保护的链接或直接通过WhatsApp/Telegram分享。",
    },
  ],
  featureItems: [
    {
      title: "多媒体拼图工作室",
      description: "在分层画布中组合照片、矢量形状、渐变背景和动画表情符号",
    },
    {
      title: "智能难度调整",
      description: "根据图像复杂度自动建议拼图数量（50-1000+块）",
    },
    {
      title: "全球发现",
      description: "按国家/文化标签筛选拼图。由我们的团队策划的每周精选集合",
    },
  ],
};

export type StaticData = typeof data;
