export function getData(locale: string) {
  const data = {
    featuresTitle: "Key Features",
    faqTitle: "Frequently Asked Questions",
    websiteTitle:
      "Jigsaw Puzzle Creator & Online Community | JIGSY - Make & Play Puzzles Worldwide",
    homeH1: "Create, Share & Solve Digital Jigsaw Puzzles",
    exploreH1: "Discover Puzzles From Around the World",
    exploreH21: "Trending Puzzles",
    exploreH22: "Newest Creations",
    createH1: "Build Your Unique Jigsaw Puzzle in 1 Steps",
    createH2: "Choose Your Canvas: Image, Color or Emoji",
    createH3: "Solve Puzzles Created by Others",
    gameH1: "Play {puzzleName} - {difficulty} Mode",
    websiteDescription:
      "Create personalized jigsaw puzzles with images, colors, emojis and text. Play puzzles made by a global community, available in multiple languages. Free online puzzle maker with real-time collaboration features.",
    websiteKeywords:
      "jigsaw puzzle maker, online puzzle creator, custom digital puzzles, play puzzles online, collaborative puzzle solving, multilingual puzzle platform",

    siteTitle: "Puzzle Challenge",
    home: "Home",
    explore: "Explore",
    puzzle: "Puzzle Editor",
    leaderboard: "Leaderboard",
    categories: "Categories",
    groups: "Groups",
    tags: "Tags",
    search: "Search Puzzles 🧩...",
    create: "Create Puzzle 🧩",
    about: "About Us",
    siteDescription:
      "Puzzle Challenge is a fun online puzzle community, let's enjoy the fun of puzzles together.",
    contact: "Contact Us",
    email: "contact@puzzlechallenge.com",
    copyright: "© 2024 Puzzle Challenge. All rights reserved.",
    createRecord: "Create Record",
    all: "All",
    draft: "Draft",
    published: "Published",
    deleted: "Deleted",
    challenge: "Challenge",
    author: "Author",
    featuredCollections: "Featured Themes",
    view: "View",
    searchError: "An error occurred during the search, please try again later",
    searchTitle: "Search Puzzles 🧩...",
    searching: "Searching...",
    previousPage: "Previous Page",
    nextPage: "Next Page",
    noResults: "No matching atoms found",
    tryDifferentKeywords: "Try using different keywords to search",
    myPuzzles: "Puzzles I Created",
    noPuzzles: "No created puzzles yet",
    createPuzzles: "Go create some puzzles",
    pageLabel: "Page {page} of {totalPages}",
    imagePuzzle: "Image Puzzle",
    solidPuzzle: "Solid Color Puzzle",
    gradientPuzzle: "Gradient Puzzle",
    emojiPuzzle: "Emoji Puzzle",
    patternPuzzle: "Pattern Puzzle",
    textPuzzle: "Text Puzzle",
    shapePuzzle: "Shape Puzzle",
    pleaseUploadImage: "Please upload image",
    atomDataValidationFailed: "Puzzle data validation failed",
    atomUpdatedSuccess: "Puzzle updated successfully",
    atomUpdatedFailed: "Puzzle update failed",
    atomCreatedSuccess: "Puzzle created successfully",
    atomCreatedFailed: "Puzzle creation failed",
    pleaseLogin: "Please login first",
    pleaseLoginDescription: "Please login to create a puzzle",
    updatePuzzle: "Update Puzzle",
    createPuzzle: "Create Puzzle",
    uploadImage: "Upload Image",
    dragDropImage: "Drag and drop image here, or",
    selectImage: "Select Image",
    supportImageFormat:
      "Support JPG, PNG, WebP formats, recommended size 1920x1080 pixels",
    selectCategory: "Select Category",
    selectEmoji: "Select Emoji",
    backgroundColor: "Background Color",
    emojiRotation: "Emoji Rotation",
    presetGradient: "Preset Gradient",
    gradientType: "Gradient Type",
    gradientColors: "Gradient Colors ({colors})",
    addColor: "Add Color",
    gradientAngle: "Gradient Angle: {angle}°",
    linearGradient: "Linear Gradient",
    radialGradient: "Radial Gradient",
    patternType: "Pattern Type",
    patternPresets: "Pattern Presets",
    patternSize: "Pattern Size: {size}px",
    patternSpacing: "Pattern Spacing: {spacing}px",
    lineWidth: "Line Width: {lineWidth}px",
    lineWidthUnit: "Line Width",
    patternRotation: "Pattern Rotation: {rotation}°",
    patternColor: "Pattern Color",
    previewEffect: "Preview Effect",
    puzzlePreview: "Puzzle Preview",
    puzzlePreviewArea: "Puzzle Preview Area",
    puzzleType: "Puzzle Type",
    expectedDifficulty: "Expected Difficulty",
    expectedUseTime: "Expected Use Time",
    puzzleSettings: "Puzzle Settings",
    puzzleTitle: "Puzzle Title",
    puzzleTitlePlaceholder: "Enter Puzzle Title",
    puzzleDescription: "Puzzle Description",
    puzzleDescriptionPlaceholder: "Enter Puzzle Description",
    puzzleCategory: "Puzzle Category",
    pleaseSelectCategory: "Please select a category",
    puzzleGroup: "Puzzle Group",
    selectGroup: "Select Group",
    searchTags: "Search Tags",
    maxAddTags: "Maximum 5 tags",
    loading: "Loading...",
    noMatchingTags: "No matching tags",
    puzzlePieces: "Puzzle Pieces",
    puzzlePiecesMoreDifficult: "More pieces, more difficult",
    customPuzzleSize: "Custom Puzzle Size",
    puzzleWidth: "Width (pixels)",
    puzzleWidthPlaceholder: "Auto",
    puzzleHeight: "Height (pixels)",
    puzzleHeightPlaceholder: "Auto",
    puzzleStyle: "Puzzle Style",
    puzzleEdgeSize: "Puzzle Edge Size",
    puzzleEdgeSizePlaceholder: "Enter Puzzle Edge Size",
    puzzleSizeNotSet: "When not set, the original image size will be used",
    puzzleTags: "Puzzle Tags",
    puzzleEdgeRandomness: "Puzzle Edge Randomness",
    puzzleSeed: "Random Seed",
    puzzleLineColor: "Puzzle Line Color",
    puzzleLineWidth: "Puzzle Line Width",
    puzzleLineWidthPlaceholder: "Enter Puzzle Line Width",
    piecesOptionLabel: "{value} Pieces ({tilesX}×{tilesY})",
    shapeType: "Shape Type",
    circle: "Circle",
    square: "Square",
    triangle: "Triangle",
    star: "Star",
    heart: "Heart",
    polygon: "Polygon",
    spiral: "Spiral",
    flower: "Flower",
    shapeSize: "Shape Size: {value}px",
    repeatMode: "Repeat Mode",
    centered: "Centered Overlap",
    tiled: "Tiled Grid",
    random: "Random Distribution",
    repeatTimes: "Repeat Times: {value}",
    repeatGap: "Repeat Gap: {value}px",
    randomRotation: "Random Rotation",
    rotation: "Rotation Angle: {value}deg",
    shapeColor: "Shape Color",
    borderWidth: "Border Width: {value}px",
    borderColor: "Border Color",
    polygonSides: "Polygon Sides: {value}",
    flowerPetals: "Flower Petals: {value}",
    mint: "Mint",
    skyBlue: "Sky Blue",
    lightPurple: "Light Purple",
    coralPink: "Coral Pink",
    goldenFlower: "Golden Flower",
    lavender: "Lavender",
    tiffanyBlue: "Tiffany Blue",
    roseRed: "Rose Red",
    lemonYellow: "Lemon Yellow",
    oceanBlue: "Ocean Blue",
    graphiteBlack: "Graphite Black",
    pearlWhite: "Pearl White",
    presetColors: "Preset Colors",
    customColor: "Custom Color",
    hexColorCode: "#HEX Color Code",
    apply: "Apply",
    textMode: "Text Mode",
    normal: "Normal Text",
    randomText: "Random Characters",
    tiledText: "Tiled Text",
    text: "Input Text",
    textPlaceholder: "Input text here...",
    textRepeat: "Repeat Times: {value}",
    randomSize: "Random Size",
    randomColor: "Random Color",
    colorVariation: "Color Variation: {value}",
    font: "Font",
    sansSerif: "Sans Serif",
    serif: "Serif",
    monospace: "Monospace",
    cursive: "Cursive",
    fantasy: "Fantasy",
    microsoftYaHei: "Microsoft YaHei",
    simSun: "SimSun",
    kaiTi: "KaiTi",
    fontSize: "Font Size: {value}px",
    alignment: "Alignment",
    left: "Left Align",
    center: "Center",
    right: "Right Align",
    bold: "Bold",
    italic: "Italic",
    textColor: "Text Color",
    useTime: "About {value} minutes",
    pieces: "{value} Pieces",
    difficulty: "{value}",
    like: "Like",
    unlike: "Unlike",
    favorite: "Favorite",
    unfavorite: "Unfavorite",
    error: "Operation failed, please try again later",
    group: "Recommended 🧩",
    share: "Share",
    featured: "Featured",
    unfeatured: "Unfeatured",
    publish: "Publish",
    unpublish: "Unpublish",
    start: "Start Puzzle",
    startGame: "Start Puzzle",
    reset: "Reset",
    exit: "Exit Game",
    complete: "Complete Puzzle",
    time: "Time",
    piecesUnit: "Pieces",
    difficultyLabel: "Difficulty",
    surrounding: "Surrounding Mode",
    surroundingDescription: "Puzzle pieces surround the canvas",
    centerScatter: "Center Scatter",
    centerScatterDescription: "Puzzle pieces scatter from the center",
    uniformDistribution: "Uniform Distribution",
    uniformDistributionDescription:
      "Puzzle pieces are uniformly distributed on the entire canvas",
    black: "Black",
    white: "White",
    gray: "Gray",
    blue: "Blue",
    green: "Green",
    red: "Red",
    restartGame: "Restart Game",
    exitGame: "Exit Game",
    completeGame: "Complete Game",
    verifyPuzzle: "Verify Puzzle",
    autoArrange: "Auto Arrange",
    selectBackgroundTexture: "Select Background Texture",
    readyToStart: "Ready to Start",
    gameSettings: "Game Settings",
    confirm: "Confirm and Restart",
    cancel: "Cancel",
    distributionStrategy: "Distribution Strategy",
    lineColor: "Line Color",
    puzzleVerified: "Puzzle Verified",
    puzzleVerifiedDescription: "Verify if the puzzle is correct",
    selectPuzzlePieces: "Select Puzzle Pieces",
    selectDistributionStrategy: "Select Distribution Strategy",
    selectLineColor: "Select Line Color",
    selectLineWidth: "Select Line Width",
    puzzleVerifiedSuccess: "Puzzle Verified Successfully",
    puzzleVerifiedFailed: "Puzzle Verification Failed",
    continue: "Continue",
    pause: "Pause",
    reset2: "Reset",
    preview: "Preview",
    grid: "Grid",
    panning: "Panning Mode",
    settings: "Settings",
    freePanning: "Free Panning",
    bestTime: "Best Time",
    patternGrid: "Grid",
    patternDots: "Dots",
    patternLines: "Lines",
    patternCircles: "Circles",
    patternTriangles: "Triangles",
    patternZigzag: "Zigzag",
    patternWaves: "Waves",
    patternCheckerboard: "Checkerboard",
    patternHexagons: "Hexagons",
    patternStars: "Stars",
    patternCrosshatch: "Crosshatch",
    patternPolkaDots: "Polka Dots",
    patternDiamonds: "Diamonds",
    patternStripes: "Stripes",
    patternConfetti: "Confetti",
    patternHoneycomb: "Honeycomb",
    solid: "Solid",
    gradient: "Gradient",
    pattern: "Pattern",
    easy: "easy",
    medium: "medium",
    hard: "hard",
    veryHard: "veryHard",
    completed: "Completed",
    failed: "Failed",
    notGameRecord: "No game record",
    unknown: "Unknown",
    gameDuration: "Game Duration",
    viewDetails: "View Details",
    myGameRecord: "My Game Record",
    faqItems: [
      {
        question: "How to create a puzzle without design skills?",
        answer:
          "Our drag-and-drop editor with 50+ templates makes it easy. Add elements with one click and use AI-assisted layout suggestions.",
      },
      {
        question: "Is it free to play puzzles?",
        answer:
          "Yes! 100% free to play all community puzzles. Premium creators get analytics dashboards and commercial usage rights.",
      },
      {
        question: "How do language settings work?",
        answer:
          "Auto-translate titles/descriptions to 12 languages. Puzzle content remains in original creation language for authenticity.",
      },
      {
        question: "Mobile device compatibility?",
        answer:
          "Fully responsive on all devices. Tablet-optimized controls for puzzle solving, phone-friendly creation workflow.",
      },
      {
        question: "Can I share puzzles privately?",
        answer:
          "Yes! Generate password-protected links or share directly via WhatsApp/Telegram. Business accounts get white-label embedding.",
      },
    ],
    featureItems: [
      {
        title: "Multimedia Puzzle Studio",
        description:
          "Combine photos, vector shapes, gradient backgrounds, and animated emojis on a layered canvas",
      },
      {
        title: "Intelligent Difficulty Adjustment",
        description:
          "Automatically suggest puzzle piece numbers (50-1000+) based on image complexity",
      },
      {
        title: "Global Discovery",
        description:
          "Filter puzzles by country/cultural tags. Our team's weekly curated collections",
      },
    ],
  };

  const data2 = {
    featuresTitle: "主要功能",
    faqTitle: "常见问题",
    websiteTitle: "拼图挑战 - 在线拼图社区 | 创建和玩拼图",
    homeH1: "创建、分享和解决数字拼图",
    exploreH1: "发现世界各地的拼图",
    exploreH21: "热门拼图",
    exploreH22: "最新创作",
    createH1: "在1步中构建您的独特拼图",
    createH2: "选择您的画布：图片、颜色或表情",
    createH3: "解决其他人创建的拼图",
    gameH1: "玩 {puzzleName} - {difficulty} 模式",
    websiteDescription:
      "创建个性化拼图，使用图片、颜色、表情和文字。与全球社区一起玩拼图，支持多种语言。免费在线拼图制作器，实时协作功能。",
    websiteKeywords:
      "拼图制作器, 在线拼图制作器, 自定义数字拼图, 在线玩拼图, 协作拼图解决, 多语言拼图平台",

    completed: "胜利",
    failed: "失败",
    notGameRecord: "暂无游戏记录",
    unknown: "未知",
    gameDuration: "游戏时长",
    viewDetails: "查看详情",
    myGameRecord: "我的游戏记录",
    siteTitle: "拼图挑战",
    home: "首页",
    explore: "发现",
    puzzle: "拼图编辑器",
    leaderboard: "排行榜",
    categories: "分类",
    groups: "群组",
    tags: "标签",
    search: "搜索拼图 🧩...",
    create: "创建拼图 🧩",
    about: "关于我们",
    siteDescription:
      "拼图挑战是一个充满乐趣的在线拼图社区，让我们一起享受拼图的乐趣。",
    contact: "联系我们",
    email: "contact@puzzlechallenge.com",
    copyright: "© 2024 拼图挑战. 保留所有权利.",
    createRecord: "创建记录",
    all: "全部",
    draft: "待审核",
    published: "已发布",
    deleted: "已删除",
    challenge: "挑战",
    author: "作者",
    featuredCollections: "精选主题",
    view: "查看",
    searchError: "搜索过程中发生错误，请稍后重试",
    searchTitle: "搜索拼图 🧩...",
    searching: "搜索中...",
    previousPage: "上一页",
    nextPage: "下一页",
    noResults: "未找到匹配的原子",
    tryDifferentKeywords: "尝试使用不同的关键词搜索",
    myPuzzles: "我创建的拼图",
    noPuzzles: "暂无创建拼图",
    createPuzzles: "去创建一些拼图吧",
    pageLabel: "第 {page} 页，共 {totalPages} 页",
    imagePuzzle: "图片拼图",
    solidPuzzle: "纯色拼图",
    gradientPuzzle: "渐变拼图",
    emojiPuzzle: "Emoji拼图",
    patternPuzzle: "图案拼图",
    textPuzzle: "文字拼图",
    shapePuzzle: "形状拼图",
    pleaseUploadImage: "请先上传图片",
    atomDataValidationFailed: "拼图数据验证失败",
    atomUpdatedSuccess: "拼图更新成功",
    atomUpdatedFailed: "拼图更新失败",
    atomCreatedSuccess: "拼图创建成功",
    atomCreatedFailed: "拼图创建失败",
    pleaseLogin: "请先登录",
    pleaseLoginDescription: "请先登录，才能创建拼图",
    updatePuzzle: "更新拼图",
    createPuzzle: "创建拼图",
    uploadImage: "上传的图片",
    dragDropImage: "拖放图片到这里，或者",
    selectImage: "选择图片",
    supportImageFormat: "支持 JPG、PNG、WebP 格式，建议尺寸 1920x1080 像素",
    selectCategory: "选择分类",
    selectEmoji: "选择表情",
    backgroundColor: "背景颜色",
    emojiRotation: "旋转角度",
    presetGradient: "预设渐变",
    gradientType: "渐变类型",
    gradientColors: "渐变颜色 ({colors}个)",
    addColor: "添加颜色",
    gradientAngle: "渐变角度: {angle}°",
    linearGradient: "线性渐变",
    radialGradient: "径向渐变",
    patternType: "图案类型",
    patternPresets: "图案预设",
    patternSize: "图案大小: {size}px",
    patternSpacing: "图案间距: {spacing}px",
    lineWidth: "线条宽度: {lineWidth}px",
    patternRotation: "旋转角度: {rotation}°",
    patternColor: "图案颜色",
    previewEffect: "预览效果",
    puzzlePreview: "拼图预览",
    puzzlePreviewArea: "拼图预览区域",
    puzzleType: "拼图类型",
    expectedDifficulty: "预计难度",
    expectedUseTime: "预计用时",
    puzzleSettings: "拼图设置",
    puzzleTitle: "拼图标题",
    puzzleTitlePlaceholder: "请输入拼图标题",
    puzzleDescription: "拼图描述",
    puzzleDescriptionPlaceholder: "请输入拼图描述",
    puzzleCategory: "拼图分类",
    pleaseSelectCategory: "请先选择分类",
    puzzleGroup: "拼图分组",
    selectGroup: "选择分组",
    searchTags: "搜索标签",
    maxAddTags: "最多添加 5 个标签",
    loading: "加载中...",
    noMatchingTags: "无匹配标签",
    puzzlePieces: "拼图数量",
    puzzlePiecesMoreDifficult: "拼图数量越多，难度越大",
    customPuzzleSize: "自定义拼图尺寸",
    puzzleWidth: "宽度 (像素)",
    puzzleWidthPlaceholder: "自动",
    puzzleHeight: "高度 (像素)",
    puzzleHeightPlaceholder: "自动",
    puzzleStyle: "拼图样式",
    puzzleEdgeSize: "拼图边缘大小",
    puzzleEdgeSizePlaceholder: "请输入拼图边缘大小",
    puzzleSizeNotSet: "不设置时将使用原图尺寸",
    puzzleTags: "拼图标签",
    puzzleEdgeRandomness: "拼图边缘随机度",
    puzzleSeed: "随机种子",
    puzzleLineColor: "拼图线条颜色",
    puzzleLineWidth: "拼图线条宽度",
    puzzleLineWidthPlaceholder: "请输入拼图线条宽度",
    piecesOptionLabel: "{value} 片 ({tilesX}×{tilesY})",
    shapeType: "形状类型",
    circle: "圆形",
    square: "正方形",
    triangle: "三角形",
    star: "星形",
    heart: "心形",
    polygon: "多边形",
    spiral: "螺旋",
    flower: "花朵",
    shapeSize: "图形大小: {value}px",
    repeatMode: "重复模式",
    centered: "居中重叠",
    tiled: "网格平铺",
    random: "随机分布",
    repeatTimes: "图形重复次数: {value}",
    repeatGap: "重复间距: {value}px",
    randomRotation: "随机旋转",
    rotation: "旋转角度: {value}deg",
    shapeColor: "图形颜色",
    borderWidth: "边框宽度: {value}px",
    borderColor: "边框颜色",
    polygonSides: "多边形边数: {value}",
    flowerPetals: "花朵花瓣数: {value}",
    mint: "薄荷绿",
    skyBlue: "天空蓝",
    lightPurple: "淡紫色",
    coralPink: "珊瑚粉",
    goldenFlower: "金盏花",
    lavender: "薰衣草",
    tiffanyBlue: "蒂芙尼蓝",
    roseRed: "玫瑰红",
    lemonYellow: "柠檬黄",
    oceanBlue: "海洋蓝",
    graphiteBlack: "石墨黑",
    pearlWhite: "珍珠白",
    presetColors: "预设颜色",
    customColor: "自定义颜色",
    hexColorCode: "#HEX颜色码",
    apply: "应用",
    textMode: "文字模式",
    normal: "标准文本",
    randomText: "随机字符",
    tiledText: "平铺文本",
    text: "输入文字",
    textPlaceholder: "在这里输入文字...",
    textRepeat: "重复次数: {value}",
    randomSize: "随机大小",
    randomColor: "随机颜色",
    colorVariation: "颜色变化程度: {value}",
    font: "字体",
    sansSerif: "无衬线体",
    serif: "衬线体",
    monospace: "等宽字体",
    cursive: "草书",
    fantasy: "幻想体",
    microsoftYaHei: "微软雅黑",
    simSun: "宋体",
    kaiTi: "楷体",
    fontSize: "字体大小: {value}px",
    alignment: "对齐方式",
    left: "左对齐",
    center: "居中",
    right: "右对齐",
    bold: "粗体",
    italic: "斜体",
    textColor: "文字颜色",
    useTime: "约 {value} 分钟",
    pieces: "{value} 片",
    difficulty: "{value}",
    like: "点赞成功",
    unlike: "取消点赞成功",
    favorite: "收藏成功",
    unfavorite: "取消收藏成功",
    error: "操作失败，请稍后重试",
    group: "推荐🧩",
    share: "分享",
    featured: "精选",
    unfeatured: "取消精选",
    publish: "发布",
    unpublish: "取消发布",
    start: "开始拼图",
    startGame: "开始拼图",
    reset: "重新开始",
    exit: "退出游戏",
    complete: "完成拼图",
    time: "用时",
    piecesUnit: "片",
    difficultyLabel: "难度",
    surrounding: "环绕模式",
    surroundingDescription: "拼图块围绕在画布四周",
    centerScatter: "中心扩散",
    centerScatterDescription: "拼图块从中心向外散开分布",
    uniformDistribution: "均匀分散",
    uniformDistributionDescription: "拼图块均匀分布在整个画布上",
    black: "黑色",
    white: "白色",
    gray: "灰色",
    blue: "蓝色",
    green: "绿色",
    red: "红色",
    restartGame: "重新开始",
    exitGame: "退出游戏",
    completeGame: "完成拼图",
    verifyPuzzle: "验证拼图",
    autoArrange: "自动排列",
    selectBackgroundTexture: "选择背景纹理",
    readyToStart: "准备开始",
    gameSettings: "游戏设置",
    confirm: "确定并重新开始",
    cancel: "取消",
    distributionStrategy: "分布策略",
    lineColor: "线条颜色",
    puzzleVerified: "拼图验证",
    puzzleVerifiedDescription: "验证拼图是否正确",
    selectPuzzlePieces: "选择拼图数量",
    selectDistributionStrategy: "选择分布策略",
    selectLineColor: "选择线条颜色",
    selectLineWidth: "选择线条宽度",
    puzzleVerifiedSuccess: "拼图验证成功",
    puzzleVerifiedFailed: "拼图验证失败",
    continue: "继续",
    pause: "暂停",
    reset2: "重置",
    preview: "预览",
    grid: "网格",
    panning: "拖动模式",
    settings: "设置",
    freePanning: "自由拖动",
    bestTime: "最佳用时",
    patternGrid: "网格",
    patternDots: "圆点",
    patternLines: "线条",
    patternCircles: "圆环",
    patternTriangles: "三角形",
    patternZigzag: "锯齿线",
    patternWaves: "波浪线",
    patternCheckerboard: "棋盘格",
    patternHexagons: "六边形",
    patternStars: "星星",
    patternCrosshatch: "交叉线",
    patternPolkaDots: "波点",
    patternDiamonds: "菱形",
    patternStripes: "条纹",
    patternConfetti: "彩纸",
    patternHoneycomb: "蜂巢",
    solid: "纯色",
    gradient: "渐变",
    pattern: "纹理",
    easy: "简单",
    medium: "中等",
    hard: "困难",
    veryHard: "非常困难",
    faqItems: [
      {
        question: "如何在没有设计技能的情况下创建拼图？",
        answer:
          "我们的拖拽式编辑器带有50+模板，非常容易使用。只需单击添加元素，并使用AI辅助的布局建议。",
      },
      {
        question: "玩拼图是否免费？",
        answer:
          "是的！所有社区拼图100%免费玩。高级创作者获得分析仪表盘和商业使用权。",
      },
      {
        question: "语言设置如何工作？",
        answer:
          "自动将标题/描述翻译成12种语言。拼图内容保持原创语言，以确保真实性。",
      },
      {
        question: "我能私下分享拼图吗？",
        answer: "是的！生成密码保护的链接或直接通过WhatsApp/Telegram分享。",
      },
    ],
    featureItems: [
      {
        title: "多媒体拼图工作室",
        description: "在分层画布中组合照片、矢量形状、渐变背景和动画表情符号",
      },
      {
        title: "智能难度调整",
        description: "根据图像复杂度自动建议拼图数量（50-1000+块）",
      },
      {
        title: "全球发现",
        description: "按国家/文化标签筛选拼图。由我们的团队策划的每周精选集合",
      },
    ],
  };

  const newData = locale === "en" ? data : data2;

  return newData;
}
