[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm run prisma:generate",
  "pnpm run prisma:migrate:deploy",
  "pnpm run build"
]

[start]
cmd = "pnpm run start"
